version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    healthcheck:
      test: pg_isready -U postgres
      interval: 3s
      timeout: 3s
      retries: 30
  app:
    build: .
    depends_on: 
      db:
        condition: service_healthy
      migrations: 
        condition: service_completed_successfully
    ports:
      - '127.0.0.1:8080:8080'
  migrations:
    build: migrations
    depends_on:
      db:
        condition: service_healthy

