name:                web
version:             0.1.0.0
github:              "githubuser/web"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2023 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/web#readme>

dependencies:
- base >= 4.7 && < 5
- servant
- servant-server
- servant-auth
- hasql
- hasql-th
- hasql-pool
- aeson
- text
- vector
- bytestring
- mtl
- wai
- warp
- profunctors
- utf8-string
- wreq
- lens-aeson
- lens

default-extensions:
- OverloadedStrings
- QuasiQuotes
- DataKinds
- DeriveGeneric
- GeneralizedNewtypeDeriving
- DeriveFunctor
- TemplateHaskell
- TypeOperators
- FlexibleContexts

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  web-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - web

tests:
  web-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - web
